version: '3.0'

services:
  postgres:
    container_name: db_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: lumi
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: Postgres2024!
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
